
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://127.0.0.1:3306/member
    password: '1234'
  jpa:
    open-in-view: 'false'
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  redis:
    host: localhost
    port: '6379'


  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: df710263c1b8329156a9d53ee1e1e560
            client-secret: dFyaruSPhpXVJEzfbFCOLgWTCNP2rbel
            client-name: kakao
            client-authentication-method: POST
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email

          naver:
            client-id: 5H0zCpeXPZIe3OBcvvqW
            client-secret: 3P0jGzPn05
            authorizationGrantType: authorization_code
            redirectUri: "http://localhost:8080/login/oauth2/code/naver"
            scope: name, nickname, email, profile_image
            client-name: Naver

          google:
            client-id: 133194259315-jq9q81o3ipdaktlagnsqqc068cpgg4ua.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email


        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri : https://kauth.kakao.com/v2/user/me
            userNameAttribute : id

          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response



